name: 'Get & Cache Dependencies'
description: 'Get the dependencies (via npm) and cache them'
inputs:
  caching:
    description: 'Whetherto cahce dependencies or not.'
    required: false
    default: 'true'
runs: 
  using: composite
  steps:
    - name: Cache dependencies
      if  : inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Node js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      if: steps.cache.outputs.cahce-hit != 'true' || inputs.caching != 'true'
      run: npm ci
      shell: bash