name: Deploy website
on:
  # pull_request:
  #   types: 
  #     - opened
  workflow_dispatch:
  push: 
    branches:
      - main
      # - 'dev-*' # triggers on all dev-
      # - 'feature/**' # triggers on all branch that starts with feature/<any brnch>
    paths-ignore:
      - '.github/workflows/*' # will not trigger if the workflow file is changed
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm # this tells gh-action to save cache on .npm folder
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # this generates each cashe with unique id
      - name: Installing nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependecies
        run : npm ci
      - name: Lint code base
        run : npm run lint
      - name: Run test
        id  : test-run
        run : npm run test
      - name: Upload test report
        if  : failure() && steps.test-run.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with: 
          name: test-report
          path: test.json
  build: 
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.jsFile }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm # this tells gh-action to save cache on .npm folder
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }} # this generates each cashe with unique id
      - name: Installing nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Installing dependecies
        run: npm ci
      - name: Build Artifact 
        run: npm run build
      - name: Publish JS filename
        id  : publish
        run : find dist/assets/*.js -type f -execdir echo 'jsFile={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: dist-files
          path: dist
          # path: | # we need this pipe char to run multiple commands
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with: 
          name: dist-files # note this needs to needs to be the same name as above on build steps
      - name: Output contents
        run: ls
      - name: Output filename
        run : echo "${{ needs.build.outputs.script-file }}"
      - name: Deploy
        run : echo "Deploying...."
  report:
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output Information
        run: |
          echo "One of you job has failed"
          echo "${{ github }}"